version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /users/app/node_modules
      - .:/users/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /users/app/node_modules
      - .:/users/app
    command: ["npm", "run", "test"]
